name: gas

on: [push, workflow_dispatch]

env:
  FOUNDRY_SRC: V3/src
  FOUNDRY_TEST: V3/test
  FOUNDRY_SCRIPT: V3/script

jobs:
  check:
    strategy:
      fail-fast: true

    name: Run Gas Tests
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install-tools
        uses: ./.github/workflows/install-tools

      - name: Run Forge tests
        run: |
          FORGE_SNAPSHOT_CHECK=true forge test --mt testGas -vvv
        id: test
