name: lint

on: [push, workflow_dispatch]

jobs:
  lint:
    name: Static Analysis
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v5
      - name: install-tools
        uses: ./.github/workflows/install-tools

      - name: Run Forge formatter and Solhint
        run: yarn lint:check
